name: Download Gambit - CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Gambit
      run: gsc -v

  Windows-mingw:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        os: win-mingw
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Gambit
      run: gsc -v

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Gambit
      run: gsc -v

  MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Gambit
      run: gsc -v

  Boot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        os: boot
        local-path: ./
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: List Files
      run: ls -al ./boot/
