name: Download Gambit - CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./ # Use the action at root of the repo
      with:
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Gambit
      run: gsc -v
